CREATE TABLE public.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    tel_no     VARCHAR(255),
    e_mail     VARCHAR(255),
    username   VARCHAR(255),
    password   VARCHAR(255),
    role       BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role) REFERENCES public.role (id) ON DELETE CASCADE;